# sample config

data_root: <path to dataset>
train_list_path: <path to train_gestures.txt>
test_list_path:

exp:
    wandb: False
    wandb_api_key:
    proj_name: shrec-ffusion
    exp_dir: ./runs/feature_fusion_1/
    tags:
        - v1
    exp_name:
    device: auto
    log_freq: 10    # log every l_f steps
    val_freq: 5     # validate every v_f epochs; -1 means only at the end
    n_workers: 1
    pin_memory: True
    cache: False
    n_cache_workers: 4
    

hparams:
    seed: 0
    batch_size: 16
    n_epochs: 1
    l_smooth: 0.1
    
    model:
        name: feature_fusion
        block_type: bn_block
        T: 32
        D: 2
        res_in: [50, 50]
        num_classes: 14
        drop_prob: 0.5
        mlp: [128]
        
    optimizer:
        opt_type: adadelta
        opt_kwargs:
            lr: 0.3
            rho: 0.95
            eps: 0.00000001
    
    scheduler:
        n_warmup: 2
        scheduler_type:

    transforms:
        # train transforms and augmentations
        train:
            gvar:
                g_min: 155
                g_max: 255
                eta: 10
            
            resize:
                H_new: 50
                W_new: 50

            aug:
                joint_shift_scale_rotate:
                    shift_limit: 0.05
                    scale_limit: 0.05
                    rotate_limit: 10
                
                image_shift_scale_rotate:
                    shift_limit: 0.05
                    scale_limit: 0.05
                    rotate_limit: 10

        # inference transforms
        eval:
            gvar:
                g_min: 155
                g_max: 255
                eta: 10
            
            resize:
                H_new: 50
                W_new: 50

            aug:
